name: Python Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd lecture5
          pip install -r requirements.txt || true

      - name: Run tests
        run: |
          cd lecture5
          [ -d tests ] && cd tests
          pytest || true